### ISSUE TITLE
Sound.retieve() error

### ISSUE THREAD

**Issue by dr-costas** [MTG/freesound-python#17]
Hi, 

The following code:

```python
s = freesound_client.get_sound(320946)
s.retrieve(os.getcwd())
```

gives the error:
>IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7f403ade7fc8>)

Any suggestions?

**Comment by dr-costas** [comment]
OK.. I got it. Thnx!

One more question though... since I'm not interested at the .wav file but at the features that I want to extract from it, can you suggest me how can I get log mel band energies (or mel band energies) and stft's from each sound file and also let me (my script) define the windowing and overlapping parameters?

**Comment by xavierfav** [comment]
Well, the analysis are done after someone upload a sound in Freesound.
To my knowledge, they are done only once with an unique set of parameters, so you can't ask for the windowing and overlapping parameters... The solution would be (as you though so) to compute the analysis with the desired parameters yourself, after having downloaded the sounds.

**Comment by ffont** [comment]
As @xavierfav mentions the analysis is performed at upload time and therefore the only descriptors available are those computed with some fixed settings. Here you'll find some information about how the descriptors are calculated: https://www.freesound.org/docs/api/analysis_docs.html#analysis-settings (some of this might be a bit outdated, but not the main things such as settings).

We use the Essentia Freesound extractor, the code can be found here: https://github.com/MTG/essentia/tree/master/src/examples/freesound. The kind of descriptors you want are low level, therefore the window size and hop size used are 2048/1024 (see https://github.com/MTG/essentia/blob/master/src/examples/freesound/FreesoundLowlevelDescriptors.cpp#L34).

You can get a list of current available descriptors at http://freesound.org/apiv2/descriptors/, I guess what you want is `lowlevel.mfcc`.

For each descriptor you can either get statistic values (`mean`, `var`, etc. computed from the results of each frame), or you can also get the full frame-by-frame results as a `.json`file. Please check the API documentation for more details, but you basically need to add the `analysis_frames` field in any search request and this will give you a link (for each sound result) where you can download the whole frames analysis.

**Comment by bdejong** [comment]
@dr-costas @ffont @xavierfav this should really be discussed in the [mailing list](http://groups.google.com/group/freesound-api) rather than in a github ticket. I do think we need to create a ticket for the implementation of the 3-legged auth though... @xavierfav is there any chance you could create a pull request for this repo that implements this?

**Comment by ffont** [comment]
In fact it should be rather simple... we need:

- Function that returns the authorize url
- Function that takes as input an authorization code (that should be given in the authorize url or via callback) and makes a request to fs to get the access token (and refresh token)

[see api docs](https://www.freesound.org/docs/api/authentication.html)

That should be as much as we can do without "interfering" in individual app's design.
