### ISSUE TITLE
Downloads from combined search results

### ISSUE THREAD

**Issue by kdog1425** [MTG/freesound-python#19]
I receive a results page from combined search.
I then try to download, but get an error:

`'NoneType' object has no attribute 'header'`

The error appears when the FSRequest.retrieve() class method is called. (line 264 at time of writing)

I noticed a difference in the inititiation of Sound under CombinedSearchPager vs Pager, and so my fix is to change line 308:

`return Sound(self.results[key], None)`

to:

`return Sound(self.results[key], self.client)`

Is this correct, or does the error arise from misusage?

**Comment by ffont** [comment]
Thanks for spotting the bug and for the fix provided in https://github.com/MTG/freesound-python/pull/20. It has been merged.
