### ISSUE TITLE
Add authentication example using OAuth2

### ISSUE THREAD

**Issue by ffont** [MTG/freesound-python#24]
The Freesound python client in its current state accepts using standard API key/token, or using OAuth2 access token (bearer). You do that by setting the `auth_type` parameter of `set_token` to `token` or `oauth` respectively. However, the client does not provide methods to get an OAuth2 access token. This can be done using standard OAuth2 flow and is described in the API documentation https://freesound.org/docs/api/authentication.html. Nevertheless, it would still be good to add an example about how to get an OAuth2 access token, probably using the `requests` module. Ideally, we should also add helper functions to do that process, but while we don't have them an example would be useful.

**Comment by Bomme** [comment]
We have two examples in the README now.
