### ISSUE TITLE
essentia_example.py distorted recording 

### ISSUE THREAD

**Issue by erikparr** [MTG/freesound-python#3]
The record audio function in this example does not really work. Although it does successfully record, the audio is very distorted. This causes the mfcc extraction and freesound query to not really work. What could be the problem?
I'm on OS X 10.10.5

**Comment by ffont** [comment]
Hi,

Recording is done via pyaudio third party library, so the problem should not be in "our" code.
Try to make sure that the input level of the mic (as handled by the OS) is ok, and also that sample rate and format settings in essentia_example.py also match sample rate and format of your input device.
If you're on osx, you can check that in the audio and midi setup panel. Let us know if it works.
