### ISSUE TITLE
how to use filter with multiple parameters

### ISSUE THREAD

**Issue by AlexAlexAlexAlexAlexAlexAlex** [MTG/freesound-python#30]
Hello, 

I was wondering how can I input multiple parameters into the filter? I have tried many syntax variations  and none of them worked. 

 I cannot seem to find any clues online either.
```
results_pager = freesound_client.text_search(
    page_size=150,
    query="",

// I want to perform search using these two filters
    filter= " ac_single_event: true"  "created: [2020-01-01T00:00:00.00Z TO 2021-01-01T00:00:00Z]",


    sort="rating_desc",
    fields="id,name",
    )
```

Thank you for any possible thoughts on this ! I would be very grateful 

Alex

**Comment by ffont** [comment]
Hi, you need to specify the multiple filters in a single string and separate filters by spaces. See the examples in the API documentaion: https://freesound.org/docs/api/resources_apiv2.html#examples
Also in the python client examples: https://github.com/MTG/freesound-python/blob/1861ad0f557d8d567525e5c91ae9c2727f2c7959/examples.py#L88

**Comment by AlexAlexAlexAlexAlexAlexAlex** [comment]
Ah I see ! Thank you!! I think I have tried that, but because it yields 0 results even though on their own

ac_single_event: true gets me 125512 results 
and created: [2020-01-01T00:00:00.00Z TO 2021-01-01T00:00:00Z] gives 44729 results

I thought there had to be at least some overlap thus something had to be wrong. But seems like it is something else then ! ( it could be that there are no files marked as single audio event for the year 2020)

**Comment by ffont** [comment]
The audio commons analyzer has not been applied in sounds uploaded in the last 1-2 years. The analysis pipeline is being refactored and we'll add that, but ac analysis currently only is avialable for older sounds.
