### ISSUE TITLE
Some methods do not support all available request parameters

### ISSUE THREAD

**Issue by ffont** [MTG/freesound-python#4]
Some of the methods implemented in the python client lack support for available request parameters described in the [Freesound v2 API documentation](http://www.freesound.org/docs/api/resources_apiv2.html).
For example, `FreesoundClient.get_sound(sound_id)` only accepts the `sound_id` parameter, but the API also allows the use of the parameters `descriptors`, `normalized` and `fields`. In this case, get_sound should also accept a undetermined list of keyword arguments (**params) and pass them to the `FSRequest.request(...)`. 

This is a list of all the methods that currently lack support for request parameters:

- [x] FreesoundClient.get_sound (should accept `**params`)
- [x] Sound.get_analysis (only lacks `normalized`, could be added as a hardcoded argument
- [x] Sound.get_similar (should accept `**params`)
- [x] Sound.get_comments (should accept `**params`)
- [x] User.get_sounds (should accept `**params`)
- [x] User.get_packs (should accept `**params`)
- [x] User. get_bookmark_categories (should accept `**params`)
- [x] User. get_bookmark_category_sounds (should accept `**params`)
- [x] Pack. get_sounds (should accept `**params`)

Also, it would be useful to add information in the documentation about the requests parameters that each method supports according to the API docs. Specially because almost all methods support an undetermined number of keyword arguments (**params) and therefore the supported request parameters can not be guessed from the method definition.
I suggest to add a line in the docstring of every method naming a list of relevant keyword arguments along with a link to the documentation (the links are already there).

```python
def get_packs(self, **params):
        """
        Get user packs.
        Relevant params: page, page_size  <- this is the added line
        http://freesound.org/docs/api/resources_apiv2.html#user-packs
        >>> u.get_packs()
        """
        # [...]
```

**Comment by ffont** [comment]
Looks good, we should have examples of this in the examples file so it is easy to see how it works and also serves as simple and minimum testing.

**Comment by xavierfav** [comment]
Yes, we have tried all the methods with Eduardo, and we now want to add
examples before closing the issue...

2016-04-04 11:47 GMT+02:00 Frederic Font <notifications@github.com>:

**Comment by bdejong** [comment]
@xavierfav will this still be merged?

**Comment by xavierfav** [comment]
It is ok, we can close this issue
